#!/usr/bin/env python

"""Small script to spit out random words."""

from argparse import ArgumentParser
from termcolor import cprint
from worddump import juxtapose

parser = ArgumentParser(description="Juxtapose random, disparate words.")
parser.add_argument('number', metavar='N', type=int, nargs='?', default=1)

if __name__ == '__main__':
    result = parser.parse_args()
    words = (juxtapose() for word in xrange(result.number))
    output = '\n' + '\n'.join(words) + '\n'
    cprint(output, attrs=['bold'])
